/**
 * Known raw color literals in `src/app/**` that predate the Nocturne tokens,
 * as file path (relative to `src/app`) → literal count.
 *
 * This list only shrinks. When a migration removes literals from a file,
 * lower or delete its entry; `theme-color-literal-guard.spec.ts` fails until
 * the baseline matches the source exactly.
 */
export const themeColorLiteralBaseline: Readonly<Record<string, number>> = {
  'auth/google-drive/components/drive-authorization-card.tsx': 11,
  'auth/google-drive/components/drive-session-menu/drive-session-menu-panel.tsx': 21,
  'auth/google-drive/components/drive-session-menu/drive-session-menu-trigger.tsx': 14,
  'components/destination-header.tsx': 3,
  'components/drag-handle.tsx': 1,
  'components/overflow-menu-trigger/index.tsx': 1,
  'components/overflow-menu-trigger/model.ts': 2,
  'components/playback-waveform/index.tsx': 8,
  'components/queue-move-position-dialog/index.tsx': 9,
  'components/surface-icon-button.tsx': 3,
  'library/components/bottom-sheet-surface.tsx': 3,
  'library/components/centered-dialog-card.tsx': 1,
  'library/components/explorer/styles.ts': 9,
  'library/components/feedback-card-model.ts': 12,
  'library/components/interaction-style-tokens.ts': 15,
  'library/components/options-menu-sheet/index.tsx': 2,
  'library/components/saved-playlist-section-styles/action-feedback-styles.ts': 5,
  'library/components/saved-playlist-section-styles/playlist-row-styles.ts': 1,
  'library/components/saved-playlist-section-styles/section-card-styles.ts': 7,
  'library/components/saved-playlist-section-styles/shared.ts': 9,
  'library/components/saved-rehearsal-library-section/browse-source-group.tsx': 2,
  'library/components/saved-rehearsal-library-section/files-explorer-list.tsx': 5,
  'library/components/saved-rehearsal-library-section/files-view.tsx': 3,
  'library/components/saved-rehearsal-library-section/library-files-success-feedback-card.tsx': 4,
  'library/components/saved-rehearsal-library-section/styles.ts': 2,
  'library/components/section-heading.tsx': 2,
  'library/components/tag-editor-sheet/index.tsx': 5,
  'library/drive/components/drive-discovery-panel.tsx': 2,
  'library/drive/components/drive-explorer-list-styles.ts': 1,
  'library/drive/components/drive-folder-group.tsx': 5,
  'library/drive/components/drive-library-breadcrumbs.tsx': 3,
  'library/drive/components/drive-library-section-header.tsx': 3,
  'library/drive/components/drive-library-section/drive-library-content.tsx': 2,
  'library/drive/components/drive-library-source-group-styles.ts': 11,
  'library/drive/components/drive-library-status-card.tsx': 1,
  'library/drive/components/drive-search-results-panel.tsx': 2,
  'library/drive/components/drive-search-selection-toolbar.tsx': 3,
  'library/loops/components/loop-range-selector-surface/index.tsx': 1,
  'library/loops/components/loop-range-selector-surface/loop-range-selector-header.tsx': 1,
  'library/loops/components/loop-range-selector-surface/loop-range-selector-preview-card.tsx': 2,
  'library/loops/components/loop-range-selector-surface/loop-range-selector-range-card.tsx': 6,
  'library/loops/components/loop-range-selector-surface/shared.ts': 11,
  'library/loops/components/saved-loop-list-styles.ts': 1,
  'library/loops/components/saved-loop-list/saved-loop-list-row.tsx': 2,
  'library/loops/components/saved-loop-section.tsx': 1,
  'library/playlists/components/saved-track-playlist-menu-surface-styles.ts': 3,
  'library/playlists/components/saved-track-playlist-menu-surface.tsx': 1,
  'library/search/components/contextual-search-panel.tsx': 8,
  'library/search/components/library-search-controls-actions.tsx': 15,
  'library/search/components/library-search-filter-popover.tsx': 4,
  'library/search/components/recent-search-suggestions.tsx': 1,
  'library/search/components/search-highlighted-text.tsx': 1,
  'routing/playback/playback-control-cards.tsx': 4,
  'routing/playback/playback-session-mode-card.tsx': 4,
  'routing/playback/playback-surface-styles.ts': 11,
  'routing/playback/playback-surface.tsx': 1,
  'routing/shell/mobile-shell-styles.ts': 10,
  'routing/shell/mobile-shell/mobile-shell-mini-player-dock.tsx': 1,
  'routing/shell/shell-tab-bar.tsx': 1,
  'screens/add/drive-discovery-action-button.tsx': 5,
  'screens/add/drive-track-saved-feedback-card.tsx': 2,
  'screens/add/index.tsx': 1,
  'screens/drive-import-review/import-completion-section.tsx': 1,
  'screens/drive-import-review/index.tsx': 1,
  'screens/drive-import-review/mode-picker-section.tsx': 1,
};
